version: '3.8'

services:
  garv-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=True
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - garv-app-data:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 

volumes:
  garv-app-data: 